### ISSUE TITLE
Backend: queue polBird updates

### ISSUE THREAD

**Issue by BenWiederhake** [Schwenger/House-Of-Tweets#5]
From #4: Do some kind of queuing of politician-bird updates.
- Suggestion: at most one every two minutes, queue the rest, and if anyone does a duplicate, delete their newer update(s)
-  Maybe include "bird version" to make sure no politician abuses us, and forces us to eventually generate a duplicate message?

**Comment by Schwenger** [comment]
I'd suggest, we allow up to 5 changes in 5 minutes because they might misspell their bird or want to switch quite quickly while in front of the appliance. If we detect irresponsive behavior, e.g. > 5 changes in quick succession or >20 in an hour, we send out a tweet stating that we detected their fast pace in changes and do not want to spam, thus we will not acknowledge changes for a certain amount of time anymore.

I would not queue the tweets since the point of this behavior is to provide feedback, and feedback that takes too long is rather pointless.

Bird versioning, while hopefully not necessary, seems sensical.

**Comment by BenWiederhake** [comment]
Nope, too much effort, assume politicians are not actively malevolent.  (After all, no pirates in the Bundestag.)
